export { default as Home } from './Home/Home';
export { default as Navbar } from './Navbar/Navbar';
export { default as Products } from './Products/Products';
export { default as Cart } from './Cart/Cart';
export { default as Checkout } from './CheckoutForm/Checkout/Checkout';
export { default as ProductDetailPage } from './ProductDetailPage/ProductDetailPage';
export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as ThankYou } from './ThankYou/ThankYou'
export { default as Footer } from './Footer/Footer';
